# Generated by Django 5.2.1 on 2025-05-08 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubikamp', '0002_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_ownwebsite',
            field=models.BooleanField(default=False, verbose_name='website-created'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_type', models.TextField(verbose_name='type_of_the_website')),
                ('user_type', models.TextField(verbose_name='type_of_the_users')),
                ('extra_features', models.TextField(verbose_name='extra_features_needed')),
                ('sample', models.TextField(blank=True, null=True, verbose_name='sample')),
                ('color_palette', models.TextField(blank=True, null=True, verbose_name='color_palette')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='website_logo')),
                ('text_content', models.TextField(blank=True, null=True, verbose_name='text_content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
